# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>

spring:
  application:
    name: IntelBI-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/InteliBI
    username: root
    password: 2531qwer
  #RabbitMQ配置
  rabbitmq:
    host: 192.168.149.128
    port: 5672
    password: admin
    username: admin
    #配置RabbitMq连接超时时间
    connection-timeout: 1s
    template:
      retry:
        #配置失败后的重连为true，其中等待时间（1000ms），以及等待时间的次数（3次）不设置则为默认；
        enabled: true
    #添加消费者确认机制，确认方式为异步（生产者不中断等待）
    publisher-confirm-type: correlated
    publisher-returns: true

  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx

# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
#鱼聪明AI调用
yuapi:
  client:
    access-key: 3p9a3u6tutt1xvw732qfd3qehamoqtzw
    secret-key: bd73zaoj44e67laoqjgn7kvx4sisn3o2
